### ISSUE TITLE
 python scripts/create_expected.py doesn't work

### ISSUE THREAD

**Issue by m-mohr** [stactools-packages/sentinel2#176]
If I run `python scripts/create_expected.py` on main right now I get an error:

````
/mnt/c/Dev/stactools-sentinel2/tests/data-files/esa_S2B_MSIL2A_20210122T133229_N0214_R081_T22HBD_20210122T155500.SAFE
/home/mm/.local/lib/python3.10/site-packages/antimeridian/_implementation.py:391: FixWindingWarning: The exterior ring of this shape is wound clockwise. Since this is a common error in real-world geometries, this package is reversing the exterior coordinates of the input shape before running its algorithm. If you know that your input shape is correct (i.e. if your data encompasses both poles), pass `fix_winding=False`.
  FixWindingWarning.warn()
Traceback (most recent call last):
  File "/mnt/c/Dev/stactools-sentinel2/scripts/create_expected.py", line 30, in <module>
    item.save_object(include_self_link=False)
  File "/home/mm/.local/lib/python3.10/site-packages/pystac/stac_object.py", line 469, in save_object
    stac_io.save_json(dest_href, self.to_dict(include_self_link=include_self_link))
  File "/home/mm/.local/lib/python3.10/site-packages/pystac/stac_io.py", line 259, in save_json
    txt = self.json_dumps(json_dict, *args, **kwargs)
  File "/home/mm/.local/lib/python3.10/site-packages/pystac/stac_io.py", line 127, in json_dumps
    return orjson.dumps(json_dict, option=orjson.OPT_INDENT_2, **kwargs).decode(
TypeError: Type is not JSON serializable: numpy.float64
````

Ubuntu, Python 3.10.12, PySTAC 1.10.1, current main branch

**Comment by m-mohr** [comment]
On windows I don't get this error, instead:

> Could not determine resolution for C:\Dev\stactools-sentinel2\tests\data-files\S2A_OPER_MSI_L1C_TL_SGS__20181231T203637_A018414_T10SDG\B01.jp2
