### ISSUE TITLE
Item creation fails for Sentinel-2 L2A SAFE metadata from processing baseline N0208

### ISSUE THREAD

**Issue by scotjohn** [stactools-packages/sentinel2#53]
Item creation ( `stactools.sentinel2.stac.create_item()` ) fails for some (maybe most) Sentinel-2 L2A (SAFE) products with processing baseline N0208.

One example is S2A_MSIL2A_20180908T105021_N0208_R051_T31UGS_20180908T134602.SAFE (as downloaded from ESA SciHub)

```
Traceback (most recent call last):
  File "D:\nw\dev\stactools_s2\main.py", line 41, in <module>
    item = create_item(str(safe))
  File "D:\nw\apps\envs\stactools_s2\lib\site-packages\stactools\sentinel2\stac.py", line 47, in create_item
    granule_metadata = GranuleMetadata(safe_manifest.granule_metadata_href,
  File "D:\nw\apps\envs\stactools_s2\lib\site-packages\stactools\sentinel2\granule_metadata.py", line 22, in __init__
    self._root = XmlElement.from_file(href, read_href_modifier)
  File "D:\nw\apps\envs\stactools_s2\lib\site-packages\stactools\core\io\xml.py", line 178, in from_file
    text = read_text(href, read_href_modifier)
  File "D:\nw\apps\envs\stactools_s2\lib\site-packages\stactools\core\io\__init__.py", line 34, in read_text
    return StacIO.default().read_text(href)
  File "D:\nw\apps\envs\stactools_s2\lib\site-packages\pystac\stac_io.py", line 275, in read_text
    return self.read_text_from_href(href)
  File "D:\nw\apps\envs\stactools_s2\lib\site-packages\stactools\core\io\__init__.py", line 54, in read_text_from_href
    with fsspec.open(href, "r") as f:
  File "D:\nw\apps\envs\stactools_s2\lib\site-packages\fsspec\core.py", line 104, in __enter__
    f = self.fs.open(self.path, mode=mode)
  File "D:\nw\apps\envs\stactools_s2\lib\site-packages\fsspec\spec.py", line 1034, in open
    f = self._open(
  File "D:\nw\apps\envs\stactools_s2\lib\site-packages\fsspec\implementations\local.py", line 162, in _open
    return LocalFileOpener(path, mode, fs=self, **kwargs)
  File "D:\nw\apps\envs\stactools_s2\lib\site-packages\fsspec\implementations\local.py", line 260, in __init__
    self._open()
  File "D:\nw\apps\envs\stactools_s2\lib\site-packages\fsspec\implementations\local.py", line 265, in _open
    self.f = open(self.path, mode=self.mode)
FileNotFoundError: [Errno 2] No such file or directory: 'L:/ws/stacs2/input2/S2A_MSIL2A_20180908T105021_N0208_R051_T31UGS_20180908T134602.SAFE/dpc/app/facilities/PHOEBUS-core/PHOEBUS-core-3.4.317/DPC/exec/data/share/wp_in_progress/fasttrack_20180908_23/app_data/step_step_EUP_FastTrack/launch_3/.5073_1536429142130/.S2A_OPER_MSI_L2A_TL_SGS__20180908T134602_A016779_T31UGS_N02.08/GRANULE/L2A_T31UGS_A016779_20180908T105024/MTD_TL.xml'
```

**Comment by gadomski** [comment]
I can reproduce with the same item, thanks for the report. I'll be taking a look.

```shell
$ stac sentinel2 create-item ~/Downloads/S2A_MSIL2A_20180908T105021_N0208_R051_T31UGS_20180908T134602.SAFE ~/Desktop
--- >8 ---
FileNotFoundError: [Errno 2] No such file or directory: '/Users/gadomski/Downloads/S2A_MSIL2A_20180908T105021_N0208_R051_T31UGS_20180908T134602.SAFE/dpc/app/facilities/PHOEBUS-core/PHOEBUS-core-3.4.317/DPC/exec/data/share/wp_in_progress/fasttrack_20180908_23/app_data/step_step_EUP_FastTrack/launch_3/.5073_1536429142130/.S2A_OPER_MSI_L2A_TL_SGS__20180908T134602_A016779_T31UGS_N02.08/GRANULE/L2A_T31UGS_A016779_20180908T105024/MTD_TL.xml'
```

**Comment by gadomski** [comment]
Digging into the `manifest.safe` of your example, the file paths appear to be invalid (e.g. this is one of the granule metadata paths):

```xml
<dataObject ID="S2_Level-2A_Tile1_Metadata">
    <byteStream mimeType="application/xml" size="192845">
        <fileLocation locatorType="URL" href="/dpc/app/facilities/PHOEBUS-core/PHOEBUS-core-3.4.317/DPC/exec/data/share/wp_in_progress/fasttrack_20180908_23/app_data/step_step_EUP_FastTrack/launch_3/.5073_1536429142130/.S2A_OPER_MSI_L2A_TL_SGS__20180908T134602_A016779_T31UGS_N02.08/GRANULE/L2A_T31UGS_A016779_20180908T105024/MTD_TL.xml"/>
        <checksum checksumName="MD5">11fb13e46f431ad8ccf2ab2b71101070</checksum>
    </byteStream>
</dataObject>
```

This is not true for every file path, e.g. the product metadata path is ok:

```xml
<dataObject ID="S2_Level-2A_Product_Metadata">
    <byteStream mimeType="text/xml" size="53298">
        <fileLocation locatorType="URL" href="./MTD_MSIL2A.xml"/>
        <checksum checksumName="MD5">64e300da5b6d838e51f5ec06da70bbd2</checksum>
    </byteStream>
</dataObject>
```

My initial inclination is to say "garbage in, garbage out" -- it's a bad path, so an error is correct. @scotjohn do you have a sense of how prevalent these problems are, and how much they impact real-world workflows? Also, do you have a sense of how this interacts with the currently-ongoing reprocessing efforts? I wouldn't want to spend time fixing an issue that gets OBE'd by the new collection 1 processing.

**Comment by gadomski** [comment]
Closing as cant-fix.
